### ISSUE TITLE
Readme: To Run needs more info?

### ISSUE THREAD

**Issue by cheneveld** [gitcoinco/smart_contracts#3]
Steps:

1. Clone repo
2. ```npm install```
3. ```bash scripts/testrpc.bash```
4. ```truffle test```

Running the truffle tests yields the following error 

```
Error: Cannot find module './mnemonic.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigheneveld/Development/gitcoinco/smart_contracts/truffle.js:10:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Function.Config.load (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:1998:23)
    at Function.Config.detect (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:1987:15)
    at Object.run (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:209130:25)
    at Command.run (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:73999:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:208667:9)
    at __webpack_require__ (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:21:30)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:67:18
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
I noticed that a ```mnemonic.js.dist``` exists, so for shits and giggles I updated the require in [truffle.js](https://github.com/gitcoinco/smart_contracts/blob/master/truffle.js#L10) to ```mnemonic.js.dist``` to move forward.

Running ```truffle test``` yields:

```
using address: 0x94098699b74f055a5d3fd7ae0451b2ea7a1a9aa5
(node:38157) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: this.provider.sendAsync is not a function
(node:38157) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:38157) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: this.provider.sendAsync is not a function
Error: Could not find /Users/craigheneveld/Development/gitcoinco/smart_contracts/contracts/zeppelin-solidity/contracts/token/StandardToken.sol from any sources; imported from /Users/craigheneveld/Development/gitcoinco/smart_contracts/contracts/bounty/BountyIndex.sol
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:50138:23
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:66021:16
    at next (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:75933:18)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:50126:7
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:96942:5
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:75838:16
    at replenish (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:65991:25)
    at iterateeCallback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:65981:17)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:66021:16
    at ReadFileContext.callback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:96938:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:419:13)
```

Looks like I need zeppelin-solidity:

So installing globally with ```npm install -g zeppelin-solidity```.

Running ```truffle test``` again finally runs the tests properly.

Seems like 2 details are needed in the setup process ->
1. Where did mnemonic.js come from and should that be mnemonic.js.dist
2. Assumptions about global dependencies

**Comment by owocki** [comment]
does 9100e1cfde32fcc7a45ec5cfbc11df5bf8d36699 cover this?

**Comment by cheneveld** [comment]
Yep Thanks!
